package integration_test

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// TestPositioning_NoLocalFirstFraming pins the v1.0.3 threat-model
// positioning lock. The phrases "local-first", "local-only", and
// "deliberately local" reflect an obsolete framing that contradicts
// the cross-infrastructure substrate the platform actually is.
// This test is the structural tripwire that catches a drift back
// into the old language.
//
// CHANGELOG.md is intentionally excluded — historical entries are an
// immutable audit trail, not living positioning copy.
func TestPositioning_NoLocalFirstFraming(t *testing.T) {
	root := repoRoot(t)
	targets := []string{
		"README.md",
		"docs/release-history/v1.0.1.md",
		"docs/roadmap.md",
		"docs/mcp.md",
		// RUFIO.md is generated by `rufio init` (not a source file).
		// The generated primer is checked separately by primer_content_test.
		// v1.0.1 release notes moved to docs/release-history/ in Bundle F (v1.0.6.3).
	}
	prohibited := []string{"local-first", "local-only", "deliberately local"}
	for _, f := range targets {
		path := filepath.Join(root, f)
		b, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		low := strings.ToLower(string(b))
		for _, p := range prohibited {
			if strings.Contains(low, p) {
				t.Errorf("%s contains prohibited framing %q", f, p)
			}
		}
	}
}

// repoRoot resolves the repo root from this source file. Mirrors the
// pattern in internal/testutil/cli.go's repoRoot but doesn't depend
// on the testutil package's binary-build path.
func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, _ := runtime.Caller(0)
	return filepath.Join(filepath.Dir(file), "..", "..")
}
